# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-MaxMind-CreditCardFraudDetection
version:      1.3
version_from: lib/Business/MaxMind/CreditCardFraudDetection.pm
installdirs:  site
requires:
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
